window.LEADERBOARD_DATA = {
  "affiliates": [
    {
      "rank": 1,
      "name": "rb3k",
      "handle": "@rbthreek",
      "avatar": "https://unavatar.io/twitter/rbthreek",
      "tweetScore": 0,
      "botActivityScore": 1683.89,
      "total": 1683.89,
      "profileUrl": "https://x.com/rbthreek",
      "xUrl": "https://x.com/rbthreek",
      "tgHandle": "@rbthreek"
    },
    {
      "rank": 5,
      "name": "Vince",
      "handle": "@Chainriffs",
      "avatar": "https://unavatar.io/twitter/Chainriffs",
      "tweetScore": 120,
      "botActivityScore": 0,
      "total": 120,
      "profileUrl": "https://x.com/Chainriffs",
      "xUrl": "https://x.com/Chainriffs",
      "tgHandle": "@Chainriffss"
    },
    {
      "rank": 7,
      "name": "Arindewar",
      "handle": "@arindewar",
      "avatar": "https://unavatar.io/twitter/arindewar",
      "tweetScore": 89.15,
      "botActivityScore": 0,
      "total": 89.15,
      "profileUrl": "https://x.com/arindewar",
      "xUrl": "https://x.com/arindewar",
      "tgHandle": "@arrieindewarrie"
    },
    {
      "rank": 8,
      "name": "Spenny",
      "handle": "@SpennyCrypto",
      "avatar": "https://unavatar.io/twitter/SpennyCrypto",
      "tweetScore": 0,
      "botActivityScore": 79.82,
      "total": 79.82,
      "profileUrl": "https://x.com/SpennyCrypto",
      "xUrl": "https://x.com/SpennyCrypto",
      "tgHandle": "@spennypretzel"
    },
    {
      "rank": 9,
      "name": "chiron",
      "handle": "@chironchain",
      "avatar": "https://unavatar.io/twitter/chironchain",
      "tweetScore": 0,
      "botActivityScore": 59.03,
      "total": 59.03,
      "profileUrl": "https://x.com/chironchain",
      "xUrl": "https://x.com/chironchain",
      "tgHandle": "@chironthetrader"
    },
    {
      "rank": 10,
      "name": "Tyler Kenney",
      "handle": "@thebasedfrogx",
      "avatar": "https://unavatar.io/twitter/thebasedfrogx",
      "tweetScore": 0,
      "botActivityScore": 53.55,
      "total": 53.55,
      "profileUrl": "https://x.com/thebasedfrogx",
      "xUrl": "https://x.com/thebasedfrogx",
      "tgHandle": "@thebasedfrog"
    },
    {
      "rank": 13,
      "name": "Techy",
      "handle": "@techy0x",
      "avatar": "https://unavatar.io/twitter/techy0x",
      "tweetScore": 0,
      "botActivityScore": 47.21,
      "total": 47.21,
      "profileUrl": "https://x.com/techy0x",
      "xUrl": "https://x.com/techy0x",
      "tgHandle": "@techy0x"
    },
    {
      "rank": 14,
      "name": "N30",
      "handle": "@N30_cryptoo",
      "avatar": "https://unavatar.io/twitter/N30_cryptoo",
      "tweetScore": 0,
      "botActivityScore": 41.1,
      "total": 41.1,
      "profileUrl": "https://x.com/N30_cryptoo",
      "xUrl": "https://x.com/N30_cryptoo",
      "tgHandle": "@N30_CRYPTO"
    },
    {
      "rank": 16,
      "name": "MJ",
      "handle": "@Vanxyrus",
      "avatar": "https://unavatar.io/twitter/Vanxyrus",
      "tweetScore": 0,
      "botActivityScore": 38.01,
      "total": 38.01,
      "profileUrl": "https://x.com/Vanxyrus",
      "xUrl": "https://x.com/Vanxyrus",
      "tgHandle": "@Vanxyrus"
    },
    {
      "rank": 18,
      "name": "MD!3e",
      "handle": "@tibbiracer",
      "avatar": "https://unavatar.io/twitter/tibbiracer",
      "tweetScore": 30,
      "botActivityScore": 0,
      "total": 30,
      "profileUrl": "https://x.com/tibbiracer",
      "xUrl": "https://x.com/tibbiracer",
      "tgHandle": "@mDiBe89"
    },
    {
      "rank": 22,
      "name": "thegardener",
      "handle": "@thegardener777",
      "avatar": "https://unavatar.io/twitter/thegardener777",
      "tweetScore": 0,
      "botActivityScore": 26.38,
      "total": 26.38,
      "profileUrl": "https://x.com/thegardener777",
      "xUrl": "https://x.com/thegardener777",
      "tgHandle": "@thegardener777"
    },
    {
      "rank": 31,
      "name": "Flynn",
      "handle": "@Flynn_howitt",
      "avatar": "https://unavatar.io/twitter/Flynn_howitt",
      "tweetScore": 15,
      "botActivityScore": 0,
      "total": 15,
      "profileUrl": "https://x.com/Flynn_howitt",
      "xUrl": "https://x.com/Flynn_howitt",
      "tgHandle": "@Flynn180"
    },
    {
      "rank": 37,
      "name": "LC",
      "handle": "@mrLCguy",
      "avatar": "https://unavatar.io/twitter/mrLCguy",
      "tweetScore": 0,
      "botActivityScore": 6.02,
      "total": 6.02,
      "profileUrl": "https://x.com/mrlcguy",
      "xUrl": "https://x.com/mrlcguy",
      "tgHandle": "@cryptocchio0"
    },
    {
      "rank": 41,
      "name": "KAPO",
      "handle": "@KAPOTHEGOAT01",
      "avatar": "https://unavatar.io/twitter/KAPOTHEGOAT01",
      "tweetScore": 1.99,
      "botActivityScore": 0,
      "total": 1.99,
      "profileUrl": "https://x.com/KAPOTHEGOAT01",
      "xUrl": "https://x.com/KAPOTHEGOAT01",
      "tgHandle": "@LUCKYL1MG"
    },
    {
      "rank": 43,
      "name": "neolawyer 1",
      "handle": "@Neolawyer1",
      "avatar": "https://unavatar.io/twitter/Neolawyer1",
      "tweetScore": 0,
      "botActivityScore": 0.29,
      "total": 0.29,
      "profileUrl": "https://x.com/Neolawyer1",
      "xUrl": "https://x.com/Neolawyer1",
      "tgHandle": "@Neolawyer"
    }
  ],
  "weekly": [
    {
      "rank": 1,
      "name": "rb3k",
      "handle": "@rbthreek",
      "avatar": "https://unavatar.io/twitter/rbthreek",
      "tweetScore": 0,
      "botActivityScore": 172.59,
      "total": 172.59,
      "profileUrl": "https://x.com/rbthreek",
      "xUrl": "https://x.com/rbthreek",
      "tgHandle": "@rbthreek"
    },
    {
      "rank": 2,
      "name": "N30",
      "handle": "@N30_cryptoo",
      "avatar": "https://unavatar.io/twitter/N30_cryptoo",
      "tweetScore": 0,
      "botActivityScore": 136.53,
      "total": 136.53,
      "profileUrl": "https://x.com/N30_cryptoo",
      "xUrl": "https://x.com/N30_cryptoo",
      "tgHandle": "@N30_CRYPTO"
    },
    {
      "rank": 3,
      "name": "Arindewar",
      "handle": "@arindewar",
      "avatar": "https://unavatar.io/twitter/arindewar",
      "tweetScore": 74.15,
      "botActivityScore": 0,
      "total": 74.15,
      "profileUrl": "https://x.com/arindewar",
      "xUrl": "https://x.com/arindewar",
      "tgHandle": "@arrieindewarrie"
    },
    {
      "rank": 4,
      "name": "MJ",
      "handle": "@Vanxyrus",
      "avatar": "https://unavatar.io/twitter/Vanxyrus",
      "tweetScore": 0,
      "botActivityScore": 64.02,
      "total": 64.02,
      "profileUrl": "https://x.com/Vanxyrus",
      "xUrl": "https://x.com/Vanxyrus",
      "tgHandle": "@Vanxyrus"
    },
    {
      "rank": 5,
      "name": "Vince",
      "handle": "@Chainriffs",
      "avatar": "https://unavatar.io/twitter/Chainriffs",
      "tweetScore": 60,
      "botActivityScore": 0,
      "total": 60,
      "profileUrl": "https://x.com/Chainriffs",
      "xUrl": "https://x.com/Chainriffs",
      "tgHandle": "@Chainriffss"
    },
    {
      "rank": 7,
      "name": "Techy",
      "handle": "@techy0x",
      "avatar": "https://unavatar.io/twitter/techy0x",
      "tweetScore": 0,
      "botActivityScore": 47.21,
      "total": 47.21,
      "profileUrl": "https://x.com/techy0x",
      "xUrl": "https://x.com/techy0x",
      "tgHandle": "@techy0x"
    },
    {
      "rank": 9,
      "name": "LC",
      "handle": "@mrLCguy",
      "avatar": "https://unavatar.io/twitter/mrLCguy",
      "tweetScore": 0,
      "botActivityScore": 29.04,
      "total": 29.04,
      "profileUrl": "https://x.com/mrlcguy",
      "xUrl": "https://x.com/mrlcguy",
      "tgHandle": "@cryptocchio0"
    },
    {
      "rank": 10,
      "name": "thegardener",
      "handle": "@thegardener777",
      "avatar": "https://unavatar.io/twitter/thegardener777",
      "tweetScore": 0,
      "botActivityScore": 26.38,
      "total": 26.38,
      "profileUrl": "https://x.com/thegardener777",
      "xUrl": "https://x.com/thegardener777",
      "tgHandle": "@thegardener777"
    },
    {
      "rank": 11,
      "name": "chiron",
      "handle": "@chironchain",
      "avatar": "https://unavatar.io/twitter/chironchain",
      "tweetScore": 0,
      "botActivityScore": 21.2,
      "total": 21.2,
      "profileUrl": "https://x.com/chironchain",
      "xUrl": "https://x.com/chironchain",
      "tgHandle": "@chironthetrader"
    },
    {
      "rank": 12,
      "name": "neolawyer 1",
      "handle": "@Neolawyer1",
      "avatar": "https://unavatar.io/twitter/Neolawyer1",
      "tweetScore": 0,
      "botActivityScore": 20.83,
      "total": 20.83,
      "profileUrl": "https://x.com/Neolawyer1",
      "xUrl": "https://x.com/Neolawyer1",
      "tgHandle": "@Neolawyer"
    },
    {
      "rank": 13,
      "name": "Flynn",
      "handle": "@Flynn_howitt",
      "avatar": "https://unavatar.io/twitter/Flynn_howitt",
      "tweetScore": 15,
      "botActivityScore": 0,
      "total": 15,
      "profileUrl": "https://x.com/Flynn_howitt",
      "xUrl": "https://x.com/Flynn_howitt",
      "tgHandle": "@Flynn180"
    },
    {
      "rank": 14,
      "name": "MJ",
      "handle": "@Vanxyrus",
      "avatar": "https://unavatar.io/twitter/Vanxyrus",
      "tweetScore": 14.86,
      "botActivityScore": 0,
      "total": 14.86,
      "profileUrl": "https://x.com/Vanxyrus",
      "xUrl": "https://x.com/Vanxyrus",
      "tgHandle": "@Vanxyrus"
    },
    {
      "rank": 15,
      "name": "Tyler Kenney",
      "handle": "@thebasedfrogx",
      "avatar": "https://unavatar.io/twitter/thebasedfrogx",
      "tweetScore": 0,
      "botActivityScore": 4.76,
      "total": 4.76,
      "profileUrl": "https://x.com/thebasedfrogx",
      "xUrl": "https://x.com/thebasedfrogx",
      "tgHandle": "@thebasedfrog"
    },
    {
      "rank": 16,
      "name": "N30",
      "handle": "@N30_cryptoo",
      "avatar": "https://unavatar.io/twitter/N30_cryptoo",
      "tweetScore": 4.3,
      "botActivityScore": 0,
      "total": 4.3,
      "profileUrl": "https://x.com/N30_cryptoo",
      "xUrl": "https://x.com/N30_cryptoo",
      "tgHandle": "@N30_CRYPTO"
    },
    {
      "rank": 17,
      "name": "Spenny",
      "handle": "@SpennyCrypto",
      "avatar": "https://unavatar.io/twitter/SpennyCrypto",
      "tweetScore": 0,
      "botActivityScore": 0.97,
      "total": 0.97,
      "profileUrl": "https://x.com/SpennyCrypto",
      "xUrl": "https://x.com/SpennyCrypto",
      "tgHandle": "@spennypretzel"
    },
    {
      "rank": 30,
      "name": "MD!3e",
      "handle": "@tibbiracer",
      "avatar": "https://unavatar.io/twitter/tibbiracer",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/tibbiracer",
      "xUrl": "https://x.com/tibbiracer",
      "tgHandle": "@mDiBe89"
    },
    {
      "rank": 43,
      "name": "KAPO",
      "handle": "@KAPOTHEGOAT01",
      "avatar": "https://unavatar.io/twitter/KAPOTHEGOAT01",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/KAPOTHEGOAT01",
      "xUrl": "https://x.com/KAPOTHEGOAT01",
      "tgHandle": "@LUCKYL1MG"
    },
    {
      "rank": 46,
      "name": "Spenny",
      "handle": "@SpennyCrypto",
      "avatar": "https://unavatar.io/twitter/SpennyCrypto",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/SpennyCrypto",
      "xUrl": "https://x.com/SpennyCrypto",
      "tgHandle": "@spennypretzel"
    }
  ],
  "monthly": [
    {
      "rank": 1,
      "name": "rb3k",
      "handle": "@rbthreek",
      "avatar": "https://unavatar.io/twitter/rbthreek",
      "tweetScore": 0,
      "botActivityScore": 1683.89,
      "total": 1683.89,
      "profileUrl": "https://x.com/rbthreek",
      "xUrl": "https://x.com/rbthreek",
      "tgHandle": "@rbthreek"
    },
    {
      "rank": 5,
      "name": "Vince",
      "handle": "@Chainriffs",
      "avatar": "https://unavatar.io/twitter/Chainriffs",
      "tweetScore": 120,
      "botActivityScore": 0,
      "total": 120,
      "profileUrl": "https://x.com/Chainriffs",
      "xUrl": "https://x.com/Chainriffs",
      "tgHandle": "@Chainriffss"
    },
    {
      "rank": 7,
      "name": "Arindewar",
      "handle": "@arindewar",
      "avatar": "https://unavatar.io/twitter/arindewar",
      "tweetScore": 89.15,
      "botActivityScore": 0,
      "total": 89.15,
      "profileUrl": "https://x.com/arindewar",
      "xUrl": "https://x.com/arindewar",
      "tgHandle": "@arrieindewarrie"
    },
    {
      "rank": 8,
      "name": "Spenny",
      "handle": "@SpennyCrypto",
      "avatar": "https://unavatar.io/twitter/SpennyCrypto",
      "tweetScore": 0,
      "botActivityScore": 79.82,
      "total": 79.82,
      "profileUrl": "https://x.com/SpennyCrypto",
      "xUrl": "https://x.com/SpennyCrypto",
      "tgHandle": "@spennypretzel"
    },
    {
      "rank": 9,
      "name": "chiron",
      "handle": "@chironchain",
      "avatar": "https://unavatar.io/twitter/chironchain",
      "tweetScore": 0,
      "botActivityScore": 59.03,
      "total": 59.03,
      "profileUrl": "https://x.com/chironchain",
      "xUrl": "https://x.com/chironchain",
      "tgHandle": "@chironthetrader"
    },
    {
      "rank": 10,
      "name": "Tyler Kenney",
      "handle": "@thebasedfrogx",
      "avatar": "https://unavatar.io/twitter/thebasedfrogx",
      "tweetScore": 0,
      "botActivityScore": 53.55,
      "total": 53.55,
      "profileUrl": "https://x.com/thebasedfrogx",
      "xUrl": "https://x.com/thebasedfrogx",
      "tgHandle": "@thebasedfrog"
    },
    {
      "rank": 13,
      "name": "Techy",
      "handle": "@techy0x",
      "avatar": "https://unavatar.io/twitter/techy0x",
      "tweetScore": 0,
      "botActivityScore": 47.21,
      "total": 47.21,
      "profileUrl": "https://x.com/techy0x",
      "xUrl": "https://x.com/techy0x",
      "tgHandle": "@techy0x"
    },
    {
      "rank": 14,
      "name": "N30",
      "handle": "@N30_cryptoo",
      "avatar": "https://unavatar.io/twitter/N30_cryptoo",
      "tweetScore": 0,
      "botActivityScore": 41.1,
      "total": 41.1,
      "profileUrl": "https://x.com/N30_cryptoo",
      "xUrl": "https://x.com/N30_cryptoo",
      "tgHandle": "@N30_CRYPTO"
    },
    {
      "rank": 16,
      "name": "MJ",
      "handle": "@Vanxyrus",
      "avatar": "https://unavatar.io/twitter/Vanxyrus",
      "tweetScore": 0,
      "botActivityScore": 38.01,
      "total": 38.01,
      "profileUrl": "https://x.com/Vanxyrus",
      "xUrl": "https://x.com/Vanxyrus",
      "tgHandle": "@Vanxyrus"
    },
    {
      "rank": 18,
      "name": "MD!3e",
      "handle": "@tibbiracer",
      "avatar": "https://unavatar.io/twitter/tibbiracer",
      "tweetScore": 30,
      "botActivityScore": 0,
      "total": 30,
      "profileUrl": "https://x.com/tibbiracer",
      "xUrl": "https://x.com/tibbiracer",
      "tgHandle": "@mDiBe89"
    },
    {
      "rank": 22,
      "name": "thegardener",
      "handle": "@thegardener777",
      "avatar": "https://unavatar.io/twitter/thegardener777",
      "tweetScore": 0,
      "botActivityScore": 26.38,
      "total": 26.38,
      "profileUrl": "https://x.com/thegardener777",
      "xUrl": "https://x.com/thegardener777",
      "tgHandle": "@thegardener777"
    },
    {
      "rank": 31,
      "name": "Flynn",
      "handle": "@Flynn_howitt",
      "avatar": "https://unavatar.io/twitter/Flynn_howitt",
      "tweetScore": 15,
      "botActivityScore": 0,
      "total": 15,
      "profileUrl": "https://x.com/Flynn_howitt",
      "xUrl": "https://x.com/Flynn_howitt",
      "tgHandle": "@Flynn180"
    },
    {
      "rank": 35,
      "name": "MJ",
      "handle": "@Vanxyrus",
      "avatar": "https://unavatar.io/twitter/Vanxyrus",
      "tweetScore": 14.86,
      "botActivityScore": 0,
      "total": 14.86,
      "profileUrl": "https://x.com/Vanxyrus",
      "xUrl": "https://x.com/Vanxyrus",
      "tgHandle": "@Vanxyrus"
    },
    {
      "rank": 36,
      "name": "Spenny",
      "handle": "@SpennyCrypto",
      "avatar": "https://unavatar.io/twitter/SpennyCrypto",
      "tweetScore": 14.75,
      "botActivityScore": 0,
      "total": 14.75,
      "profileUrl": "https://x.com/SpennyCrypto",
      "xUrl": "https://x.com/SpennyCrypto",
      "tgHandle": "@spennypretzel"
    },
    {
      "rank": 37,
      "name": "LC",
      "handle": "@mrLCguy",
      "avatar": "https://unavatar.io/twitter/mrLCguy",
      "tweetScore": 0,
      "botActivityScore": 6.02,
      "total": 6.02,
      "profileUrl": "https://x.com/mrlcguy",
      "xUrl": "https://x.com/mrlcguy",
      "tgHandle": "@cryptocchio0"
    },
    {
      "rank": 39,
      "name": "N30",
      "handle": "@N30_cryptoo",
      "avatar": "https://unavatar.io/twitter/N30_cryptoo",
      "tweetScore": 4.3,
      "botActivityScore": 0,
      "total": 4.3,
      "profileUrl": "https://x.com/N30_cryptoo",
      "xUrl": "https://x.com/N30_cryptoo",
      "tgHandle": "@N30_CRYPTO"
    },
    {
      "rank": 41,
      "name": "KAPO",
      "handle": "@KAPOTHEGOAT01",
      "avatar": "https://unavatar.io/twitter/KAPOTHEGOAT01",
      "tweetScore": 1.99,
      "botActivityScore": 0,
      "total": 1.99,
      "profileUrl": "https://x.com/KAPOTHEGOAT01",
      "xUrl": "https://x.com/KAPOTHEGOAT01",
      "tgHandle": "@LUCKYL1MG"
    },
    {
      "rank": 43,
      "name": "neolawyer 1",
      "handle": "@Neolawyer1",
      "avatar": "https://unavatar.io/twitter/Neolawyer1",
      "tweetScore": 0,
      "botActivityScore": 0.29,
      "total": 0.29,
      "profileUrl": "https://x.com/Neolawyer1",
      "xUrl": "https://x.com/Neolawyer1",
      "tgHandle": "@Neolawyer"
    }
  ]
};
