window.LEADERBOARD_DATA = {
  "affiliates": [
    {
      "name": "Rb3k ",
      "handle": "@rbthreek",
      "avatar": "https://unavatar.io/twitter/rbthreek",
      "tweetScore": 0.0,
      "botActivityScore": 121.07,
      "total": 121.07,
      "profileUrl": "https://x.com/rbthreek",
      "xUrl": "https://x.com/rbthreek",
      "tgHandle": "@rbthreek",
      "rank": 1,
      "flexCards": []
    },
    {
      "name": "Chiron \n",
      "handle": "@chironchain",
      "avatar": "https://unavatar.io/twitter/chironchain",
      "tweetScore": 0.0,
      "botActivityScore": 40.13,
      "total": 40.13,
      "profileUrl": "https://x.com/chironchain",
      "xUrl": "https://x.com/chironchain",
      "tgHandle": "@chironthetrader",
      "rank": 2,
      "flexCards": []
    },
    {
      "name": "@KAPOTHEGOAT01\n",
      "handle": "@KAPOTHEGOAT01",
      "avatar": "https://unavatar.io/twitter/KAPOTHEGOAT01",
      "tweetScore": 20.81,
      "botActivityScore": 0.0,
      "total": 20.81,
      "profileUrl": "https://x.com/KAPOTHEGOAT01",
      "xUrl": "https://x.com/KAPOTHEGOAT01",
      "tgHandle": "@LUCKYL1MG",
      "rank": 3,
      "flexCards": []
    },
    {
      "name": "Chainriffs",
      "handle": "@Chainriffs",
      "avatar": "https://unavatar.io/twitter/Chainriffs",
      "tweetScore": 14.43,
      "botActivityScore": 0.0,
      "total": 14.43,
      "profileUrl": "https://x.com/Chainriffs",
      "xUrl": "https://x.com/Chainriffs",
      "tgHandle": "@Chainriffss",
      "rank": 4,
      "flexCards": []
    },
    {
      "name": "cryptocchio0",
      "handle": "@mrLCguy",
      "avatar": "https://unavatar.io/twitter/mrLCguy",
      "tweetScore": 6.7,
      "botActivityScore": 0.0,
      "total": 6.7,
      "profileUrl": "https://x.com/mrlcguy",
      "xUrl": "https://x.com/mrlcguy",
      "tgHandle": "@cryptocchio0",
      "rank": 5,
      "flexCards": []
    },
    {
      "name": "Premium Mind  ( @deepseektetra on X )",
      "handle": "@deepseektetra",
      "avatar": "https://unavatar.io/twitter/deepseektetra",
      "tweetScore": 4.67,
      "botActivityScore": 0.0,
      "total": 4.67,
      "profileUrl": "https://x.com/deepseektetra",
      "xUrl": "https://x.com/deepseektetra",
      "tgHandle": "@tetra528",
      "rank": 6,
      "flexCards": []
    },
    {
      "name": "N30 ",
      "handle": "@N30_cryptoo",
      "avatar": "https://unavatar.io/twitter/N30_cryptoo",
      "tweetScore": 3.39,
      "botActivityScore": 0.0,
      "total": 3.39,
      "profileUrl": "https://x.com/N30_cryptoo",
      "xUrl": "https://x.com/N30_cryptoo",
      "tgHandle": "@N30_CRYPTO",
      "rank": 7,
      "flexCards": []
    },
    {
      "name": "Tyler Kenny ",
      "handle": "@thebasedfrogx",
      "avatar": "https://unavatar.io/twitter/thebasedfrogx",
      "tweetScore": 0.0,
      "botActivityScore": 3.32,
      "total": 3.32,
      "profileUrl": "https://x.com/thebasedfrogx",
      "xUrl": "https://x.com/thebasedfrogx",
      "tgHandle": "@thebasedfrog",
      "rank": 8,
      "flexCards": []
    },
    {
      "name": "cryptic_t",
      "handle": "@cryptic_tits",
      "avatar": "https://unavatar.io/twitter/cryptic_tits",
      "tweetScore": 0.69,
      "botActivityScore": 0.0,
      "total": 0.69,
      "profileUrl": "https://x.com/cryptic_tits",
      "xUrl": "https://x.com/cryptic_tits",
      "tgHandle": "@cryptic_t",
      "rank": 9,
      "flexCards": []
    },
    {
      "name": "neo lawyer ",
      "handle": "@Neolawyer1",
      "avatar": "https://unavatar.io/twitter/Neolawyer1",
      "tweetScore": 0.0,
      "botActivityScore": 0.02,
      "total": 0.02,
      "profileUrl": "https://x.com/Neolawyer1",
      "xUrl": "https://x.com/Neolawyer1",
      "tgHandle": "@Neolawyer",
      "rank": 10,
      "flexCards": []
    },
    {
      "name": "Base Pop",
      "handle": "@KD11201",
      "avatar": "https://unavatar.io/twitter/KD11201",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/KD11201",
      "xUrl": "https://x.com/KD11201",
      "tgHandle": "@Kd11201",
      "rank": 11,
      "flexCards": []
    },
    {
      "name": "Anderson",
      "handle": "@0x7_anderson",
      "avatar": "https://unavatar.io/twitter/0x7_anderson",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/0x7_anderson",
      "xUrl": "https://x.com/0x7_anderson",
      "tgHandle": "@tarcioanderson",
      "rank": 12,
      "flexCards": []
    },
    {
      "name": "Thegardner",
      "handle": "@thegardener777",
      "avatar": "https://unavatar.io/twitter/thegardener777",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/thegardener777",
      "xUrl": "https://x.com/thegardener777",
      "tgHandle": "@thegardener777",
      "rank": 13,
      "flexCards": []
    },
    {
      "name": "Karaiso",
      "handle": "@karaiso4",
      "avatar": "https://unavatar.io/twitter/karaiso4",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/karaiso4",
      "xUrl": "https://x.com/karaiso4",
      "tgHandle": "@karaiso",
      "rank": 14,
      "flexCards": []
    },
    {
      "name": "Math",
      "handle": "@mathburn666",
      "avatar": "https://unavatar.io/twitter/mathburn666",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/mathburn666",
      "xUrl": "https://x.com/mathburn666",
      "tgHandle": "@mathburn666",
      "rank": 15,
      "flexCards": []
    },
    {
      "name": "SexCaliber ",
      "handle": "@Sexcalibur31",
      "avatar": "https://unavatar.io/twitter/Sexcalibur31",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/Sexcalibur31",
      "xUrl": "https://x.com/Sexcalibur31",
      "tgHandle": "@sexcalibur31",
      "rank": 16,
      "flexCards": []
    },
    {
      "name": "RN03xx",
      "handle": "@_RN03xx_",
      "avatar": "https://unavatar.io/twitter/_RN03xx_",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/_RN03xx_",
      "xUrl": "https://x.com/_RN03xx_",
      "tgHandle": "@RN03xx",
      "rank": 17,
      "flexCards": []
    },
    {
      "name": "Borny ",
      "handle": "@unborninfinite",
      "avatar": "https://unavatar.io/twitter/unborninfinite",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/unborninfinite",
      "xUrl": "https://x.com/unborninfinite",
      "tgHandle": "@veryborny",
      "rank": 18,
      "flexCards": []
    },
    {
      "name": "poorad",
      "handle": "@Pooorad",
      "avatar": "https://unavatar.io/twitter/Pooorad",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/Pooorad",
      "xUrl": "https://x.com/Pooorad",
      "tgHandle": "@I_Love_Dogs21",
      "rank": 19,
      "flexCards": []
    },
    {
      "name": "AltcoinMiyagi",
      "handle": "@AltcoinMiyagi",
      "avatar": "https://unavatar.io/twitter/AltcoinMiyagi",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/AltcoinMiyagi",
      "xUrl": "https://x.com/AltcoinMiyagi",
      "tgHandle": "@altcoinmiyagi",
      "rank": 20,
      "flexCards": []
    },
    {
      "name": "acespades34",
      "handle": "@acespades34",
      "avatar": "https://ui-avatars.com/api/?name=acespades34",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "no x link ",
      "xUrl": "no x link ",
      "tgHandle": "5200281793",
      "rank": 21,
      "flexCards": []
    },
    {
      "name": "Alf ",
      "handle": "@alfy11116",
      "avatar": "https://unavatar.io/twitter/alfy11116",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/alfy11116",
      "xUrl": "https://x.com/alfy11116",
      "tgHandle": "@aLfy116",
      "rank": 22,
      "flexCards": []
    },
    {
      "name": "Flynn ",
      "handle": "@Flynn_howitt",
      "avatar": "https://unavatar.io/twitter/Flynn_howitt",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/Flynn_howitt",
      "xUrl": "https://x.com/Flynn_howitt",
      "tgHandle": "@Flynn180",
      "rank": 23,
      "flexCards": []
    },
    {
      "name": "Mj (@vanxryus on X) ",
      "handle": "@Vanxyrus",
      "avatar": "https://unavatar.io/twitter/Vanxyrus",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/Vanxyrus",
      "xUrl": "https://x.com/Vanxyrus",
      "tgHandle": "@Vanxyrus",
      "rank": 24,
      "flexCards": []
    },
    {
      "name": "Medbdy",
      "handle": "@medbdy",
      "avatar": "https://unavatar.io/twitter/medbdy",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/medbdy",
      "xUrl": "https://x.com/medbdy",
      "tgHandle": "@Medbdy7",
      "rank": 25,
      "flexCards": []
    },
    {
      "name": "Zeus ",
      "handle": "@vlagudfsfjr",
      "avatar": "https://unavatar.io/twitter/vlagudfsfjr",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/vlagudfsfjr",
      "xUrl": "https://x.com/vlagudfsfjr",
      "tgHandle": "@zeus4r",
      "rank": 26,
      "flexCards": []
    },
    {
      "name": "Shake ",
      "handle": "@Shake51_",
      "avatar": "https://unavatar.io/twitter/Shake51_",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/Shake51_",
      "xUrl": "https://x.com/Shake51_",
      "tgHandle": "@Shake51",
      "rank": 27,
      "flexCards": []
    },
    {
      "name": "Social Block ",
      "handle": "@socialblock",
      "avatar": "https://ui-avatars.com/api/?name=Social+Block+",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "no X link",
      "xUrl": "no X link",
      "tgHandle": "8349346803",
      "rank": 28,
      "flexCards": []
    },
    {
      "name": "DJ (@NLinker777 on X )",
      "handle": "@NLinker777",
      "avatar": "https://unavatar.io/twitter/NLinker777",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/NLinker777",
      "xUrl": "https://x.com/NLinker777",
      "tgHandle": "@JIHANWOOOO",
      "rank": 29,
      "flexCards": []
    },
    {
      "name": "Spenny",
      "handle": "@SpennyCrypto",
      "avatar": "https://unavatar.io/twitter/SpennyCrypto",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/SpennyCrypto",
      "xUrl": "https://x.com/SpennyCrypto",
      "tgHandle": "@spennypretzel",
      "rank": 30,
      "flexCards": []
    },
    {
      "name": "Nouyarao",
      "handle": "@sentientom",
      "avatar": "https://unavatar.io/twitter/sentientom",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/sentientom",
      "xUrl": "https://x.com/sentientom",
      "tgHandle": "@Nouyarao",
      "rank": 31,
      "flexCards": []
    },
    {
      "name": "mDiBe89",
      "handle": "@tibbiracer",
      "avatar": "https://unavatar.io/twitter/tibbiracer",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/tibbiracer",
      "xUrl": "https://x.com/tibbiracer",
      "tgHandle": "@mDiBe89",
      "rank": 32,
      "flexCards": []
    },
    {
      "name": "Debankind ",
      "handle": "@DebankinDad",
      "avatar": "https://unavatar.io/twitter/DebankinDad",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/DebankinDad",
      "xUrl": "https://x.com/DebankinDad",
      "tgHandle": "DebankinDad",
      "rank": 33,
      "flexCards": []
    },
    {
      "name": "3Dmax",
      "handle": "@3DMax_Virtuals",
      "avatar": "https://unavatar.io/twitter/3DMax_Virtuals",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/3DMax_Virtuals",
      "xUrl": "https://x.com/3DMax_Virtuals",
      "tgHandle": "@oO_3Dmax",
      "rank": 34,
      "flexCards": []
    },
    {
      "name": "arindewar",
      "handle": "@arindewar",
      "avatar": "https://unavatar.io/twitter/arindewar",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/arindewar",
      "xUrl": "https://x.com/arindewar",
      "tgHandle": "@arrieindewarrie",
      "rank": 35,
      "flexCards": []
    },
    {
      "name": "jeyojeyojeyo and fast are one and the same",
      "handle": "@jeyojeyojeyoandfastareoneandthesame",
      "avatar": "https://ui-avatars.com/api/?name=jeyojeyojeyo+and+fast+are+one+and+the+same",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "no X link ",
      "xUrl": "no X link ",
      "tgHandle": "351175795",
      "rank": 36,
      "flexCards": []
    },
    {
      "name": "BigHammer ",
      "handle": "@joebangsjr",
      "avatar": "https://unavatar.io/twitter/joebangsjr",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/joebangsjr",
      "xUrl": "https://x.com/joebangsjr",
      "tgHandle": "@BigHammer",
      "rank": 37,
      "flexCards": []
    },
    {
      "name": "AltcoinMatcha",
      "handle": "@AltcoinMatcha",
      "avatar": "https://unavatar.io/twitter/AltcoinMatcha",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/AltcoinMatcha",
      "xUrl": "https://x.com/AltcoinMatcha",
      "tgHandle": "@AltcoinMatcha",
      "rank": 38,
      "flexCards": []
    },
    {
      "name": "Lyvo",
      "handle": "@LyvoCrypto",
      "avatar": "https://unavatar.io/twitter/LyvoCrypto",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/lyvocrypto",
      "xUrl": "https://x.com/lyvocrypto",
      "tgHandle": "@LyvoCrypto",
      "rank": 39,
      "flexCards": []
    },
    {
      "name": "Techy0x",
      "handle": "@techy0x",
      "avatar": "https://unavatar.io/twitter/techy0x",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/techy0x",
      "xUrl": "https://x.com/techy0x",
      "tgHandle": "@techy0x",
      "rank": 40,
      "flexCards": []
    },
    {
      "name": "Don_Sama_1",
      "handle": "@Don_Sama_1",
      "avatar": "https://unavatar.io/twitter/Don_Sama_1",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/Don_Sama_1",
      "xUrl": "https://x.com/Don_Sama_1",
      "tgHandle": "1156835258",
      "rank": 41,
      "flexCards": []
    },
    {
      "name": "jyprop",
      "handle": "@prolabch",
      "avatar": "https://unavatar.io/twitter/prolabch",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/prolabch",
      "xUrl": "https://x.com/prolabch",
      "tgHandle": "@jyprop",
      "rank": 42,
      "flexCards": []
    },
    {
      "name": "Devdosomething ",
      "handle": "@devdosomething",
      "avatar": "https://unavatar.io/twitter/devdosomething",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/devdosomething",
      "xUrl": "https://x.com/devdosomething",
      "tgHandle": "@Devdosomething",
      "rank": 43,
      "flexCards": []
    }
  ],
  "weekly": [
    {
      "name": "Rb3k ",
      "handle": "@rbthreek",
      "avatar": "https://unavatar.io/twitter/rbthreek",
      "tweetScore": 0.0,
      "botActivityScore": 121.07,
      "total": 121.07,
      "profileUrl": "https://x.com/rbthreek",
      "xUrl": "https://x.com/rbthreek",
      "tgHandle": "@rbthreek",
      "rank": 1,
      "flexCards": []
    },
    {
      "name": "Chiron \n",
      "handle": "@chironchain",
      "avatar": "https://unavatar.io/twitter/chironchain",
      "tweetScore": 0.0,
      "botActivityScore": 40.13,
      "total": 40.13,
      "profileUrl": "https://x.com/chironchain",
      "xUrl": "https://x.com/chironchain",
      "tgHandle": "@chironthetrader",
      "rank": 2,
      "flexCards": []
    },
    {
      "name": "@KAPOTHEGOAT01\n",
      "handle": "@KAPOTHEGOAT01",
      "avatar": "https://unavatar.io/twitter/KAPOTHEGOAT01",
      "tweetScore": 20.81,
      "botActivityScore": 0.0,
      "total": 20.81,
      "profileUrl": "https://x.com/KAPOTHEGOAT01",
      "xUrl": "https://x.com/KAPOTHEGOAT01",
      "tgHandle": "@LUCKYL1MG",
      "rank": 3,
      "flexCards": []
    },
    {
      "name": "Chainriffs",
      "handle": "@Chainriffs",
      "avatar": "https://unavatar.io/twitter/Chainriffs",
      "tweetScore": 14.43,
      "botActivityScore": 0.0,
      "total": 14.43,
      "profileUrl": "https://x.com/Chainriffs",
      "xUrl": "https://x.com/Chainriffs",
      "tgHandle": "@Chainriffss",
      "rank": 4,
      "flexCards": []
    },
    {
      "name": "cryptocchio0",
      "handle": "@mrLCguy",
      "avatar": "https://unavatar.io/twitter/mrLCguy",
      "tweetScore": 6.7,
      "botActivityScore": 0.0,
      "total": 6.7,
      "profileUrl": "https://x.com/mrlcguy",
      "xUrl": "https://x.com/mrlcguy",
      "tgHandle": "@cryptocchio0",
      "rank": 5,
      "flexCards": []
    },
    {
      "name": "Premium Mind  ( @deepseektetra on X )",
      "handle": "@deepseektetra",
      "avatar": "https://unavatar.io/twitter/deepseektetra",
      "tweetScore": 4.67,
      "botActivityScore": 0.0,
      "total": 4.67,
      "profileUrl": "https://x.com/deepseektetra",
      "xUrl": "https://x.com/deepseektetra",
      "tgHandle": "@tetra528",
      "rank": 6,
      "flexCards": []
    },
    {
      "name": "N30 ",
      "handle": "@N30_cryptoo",
      "avatar": "https://unavatar.io/twitter/N30_cryptoo",
      "tweetScore": 3.39,
      "botActivityScore": 0.0,
      "total": 3.39,
      "profileUrl": "https://x.com/N30_cryptoo",
      "xUrl": "https://x.com/N30_cryptoo",
      "tgHandle": "@N30_CRYPTO",
      "rank": 7,
      "flexCards": []
    },
    {
      "name": "Tyler Kenny ",
      "handle": "@thebasedfrogx",
      "avatar": "https://unavatar.io/twitter/thebasedfrogx",
      "tweetScore": 0.0,
      "botActivityScore": 3.32,
      "total": 3.32,
      "profileUrl": "https://x.com/thebasedfrogx",
      "xUrl": "https://x.com/thebasedfrogx",
      "tgHandle": "@thebasedfrog",
      "rank": 8,
      "flexCards": []
    },
    {
      "name": "cryptic_t",
      "handle": "@cryptic_tits",
      "avatar": "https://unavatar.io/twitter/cryptic_tits",
      "tweetScore": 0.69,
      "botActivityScore": 0.0,
      "total": 0.69,
      "profileUrl": "https://x.com/cryptic_tits",
      "xUrl": "https://x.com/cryptic_tits",
      "tgHandle": "@cryptic_t",
      "rank": 9,
      "flexCards": []
    },
    {
      "name": "neo lawyer ",
      "handle": "@Neolawyer1",
      "avatar": "https://unavatar.io/twitter/Neolawyer1",
      "tweetScore": 0.0,
      "botActivityScore": 0.02,
      "total": 0.02,
      "profileUrl": "https://x.com/Neolawyer1",
      "xUrl": "https://x.com/Neolawyer1",
      "tgHandle": "@Neolawyer",
      "rank": 10,
      "flexCards": []
    },
    {
      "name": "Base Pop",
      "handle": "@KD11201",
      "avatar": "https://unavatar.io/twitter/KD11201",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/KD11201",
      "xUrl": "https://x.com/KD11201",
      "tgHandle": "@Kd11201",
      "rank": 11,
      "flexCards": []
    },
    {
      "name": "Anderson",
      "handle": "@0x7_anderson",
      "avatar": "https://unavatar.io/twitter/0x7_anderson",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/0x7_anderson",
      "xUrl": "https://x.com/0x7_anderson",
      "tgHandle": "@tarcioanderson",
      "rank": 12,
      "flexCards": []
    },
    {
      "name": "Thegardner",
      "handle": "@thegardener777",
      "avatar": "https://unavatar.io/twitter/thegardener777",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/thegardener777",
      "xUrl": "https://x.com/thegardener777",
      "tgHandle": "@thegardener777",
      "rank": 13,
      "flexCards": []
    },
    {
      "name": "Karaiso",
      "handle": "@karaiso4",
      "avatar": "https://unavatar.io/twitter/karaiso4",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/karaiso4",
      "xUrl": "https://x.com/karaiso4",
      "tgHandle": "@karaiso",
      "rank": 14,
      "flexCards": []
    },
    {
      "name": "Math",
      "handle": "@mathburn666",
      "avatar": "https://unavatar.io/twitter/mathburn666",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/mathburn666",
      "xUrl": "https://x.com/mathburn666",
      "tgHandle": "@mathburn666",
      "rank": 15,
      "flexCards": []
    },
    {
      "name": "SexCaliber ",
      "handle": "@Sexcalibur31",
      "avatar": "https://unavatar.io/twitter/Sexcalibur31",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/Sexcalibur31",
      "xUrl": "https://x.com/Sexcalibur31",
      "tgHandle": "@sexcalibur31",
      "rank": 16,
      "flexCards": []
    },
    {
      "name": "RN03xx",
      "handle": "@_RN03xx_",
      "avatar": "https://unavatar.io/twitter/_RN03xx_",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/_RN03xx_",
      "xUrl": "https://x.com/_RN03xx_",
      "tgHandle": "@RN03xx",
      "rank": 17,
      "flexCards": []
    },
    {
      "name": "Borny ",
      "handle": "@unborninfinite",
      "avatar": "https://unavatar.io/twitter/unborninfinite",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/unborninfinite",
      "xUrl": "https://x.com/unborninfinite",
      "tgHandle": "@veryborny",
      "rank": 18,
      "flexCards": []
    },
    {
      "name": "poorad",
      "handle": "@Pooorad",
      "avatar": "https://unavatar.io/twitter/Pooorad",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/Pooorad",
      "xUrl": "https://x.com/Pooorad",
      "tgHandle": "@I_Love_Dogs21",
      "rank": 19,
      "flexCards": []
    },
    {
      "name": "AltcoinMiyagi",
      "handle": "@AltcoinMiyagi",
      "avatar": "https://unavatar.io/twitter/AltcoinMiyagi",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/AltcoinMiyagi",
      "xUrl": "https://x.com/AltcoinMiyagi",
      "tgHandle": "@altcoinmiyagi",
      "rank": 20,
      "flexCards": []
    },
    {
      "name": "acespades34",
      "handle": "@acespades34",
      "avatar": "https://ui-avatars.com/api/?name=acespades34",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "no x link ",
      "xUrl": "no x link ",
      "tgHandle": "5200281793",
      "rank": 21,
      "flexCards": []
    },
    {
      "name": "Alf ",
      "handle": "@alfy11116",
      "avatar": "https://unavatar.io/twitter/alfy11116",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/alfy11116",
      "xUrl": "https://x.com/alfy11116",
      "tgHandle": "@aLfy116",
      "rank": 22,
      "flexCards": []
    },
    {
      "name": "Flynn ",
      "handle": "@Flynn_howitt",
      "avatar": "https://unavatar.io/twitter/Flynn_howitt",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/Flynn_howitt",
      "xUrl": "https://x.com/Flynn_howitt",
      "tgHandle": "@Flynn180",
      "rank": 23,
      "flexCards": []
    },
    {
      "name": "Mj (@vanxryus on X) ",
      "handle": "@Vanxyrus",
      "avatar": "https://unavatar.io/twitter/Vanxyrus",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/Vanxyrus",
      "xUrl": "https://x.com/Vanxyrus",
      "tgHandle": "@Vanxyrus",
      "rank": 24,
      "flexCards": []
    },
    {
      "name": "Medbdy",
      "handle": "@medbdy",
      "avatar": "https://unavatar.io/twitter/medbdy",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/medbdy",
      "xUrl": "https://x.com/medbdy",
      "tgHandle": "@Medbdy7",
      "rank": 25,
      "flexCards": []
    },
    {
      "name": "Zeus ",
      "handle": "@vlagudfsfjr",
      "avatar": "https://unavatar.io/twitter/vlagudfsfjr",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/vlagudfsfjr",
      "xUrl": "https://x.com/vlagudfsfjr",
      "tgHandle": "@zeus4r",
      "rank": 26,
      "flexCards": []
    },
    {
      "name": "Shake ",
      "handle": "@Shake51_",
      "avatar": "https://unavatar.io/twitter/Shake51_",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/Shake51_",
      "xUrl": "https://x.com/Shake51_",
      "tgHandle": "@Shake51",
      "rank": 27,
      "flexCards": []
    },
    {
      "name": "Social Block ",
      "handle": "@socialblock",
      "avatar": "https://ui-avatars.com/api/?name=Social+Block+",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "no X link",
      "xUrl": "no X link",
      "tgHandle": "8349346803",
      "rank": 28,
      "flexCards": []
    },
    {
      "name": "DJ (@NLinker777 on X )",
      "handle": "@NLinker777",
      "avatar": "https://unavatar.io/twitter/NLinker777",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/NLinker777",
      "xUrl": "https://x.com/NLinker777",
      "tgHandle": "@JIHANWOOOO",
      "rank": 29,
      "flexCards": []
    },
    {
      "name": "Spenny",
      "handle": "@SpennyCrypto",
      "avatar": "https://unavatar.io/twitter/SpennyCrypto",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/SpennyCrypto",
      "xUrl": "https://x.com/SpennyCrypto",
      "tgHandle": "@spennypretzel",
      "rank": 30,
      "flexCards": []
    },
    {
      "name": "Nouyarao",
      "handle": "@sentientom",
      "avatar": "https://unavatar.io/twitter/sentientom",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/sentientom",
      "xUrl": "https://x.com/sentientom",
      "tgHandle": "@Nouyarao",
      "rank": 31,
      "flexCards": []
    },
    {
      "name": "mDiBe89",
      "handle": "@tibbiracer",
      "avatar": "https://unavatar.io/twitter/tibbiracer",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/tibbiracer",
      "xUrl": "https://x.com/tibbiracer",
      "tgHandle": "@mDiBe89",
      "rank": 32,
      "flexCards": []
    },
    {
      "name": "Debankind ",
      "handle": "@DebankinDad",
      "avatar": "https://unavatar.io/twitter/DebankinDad",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/DebankinDad",
      "xUrl": "https://x.com/DebankinDad",
      "tgHandle": "DebankinDad",
      "rank": 33,
      "flexCards": []
    },
    {
      "name": "3Dmax",
      "handle": "@3DMax_Virtuals",
      "avatar": "https://unavatar.io/twitter/3DMax_Virtuals",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/3DMax_Virtuals",
      "xUrl": "https://x.com/3DMax_Virtuals",
      "tgHandle": "@oO_3Dmax",
      "rank": 34,
      "flexCards": []
    },
    {
      "name": "arindewar",
      "handle": "@arindewar",
      "avatar": "https://unavatar.io/twitter/arindewar",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/arindewar",
      "xUrl": "https://x.com/arindewar",
      "tgHandle": "@arrieindewarrie",
      "rank": 35,
      "flexCards": []
    },
    {
      "name": "jeyojeyojeyo and fast are one and the same",
      "handle": "@jeyojeyojeyoandfastareoneandthesame",
      "avatar": "https://ui-avatars.com/api/?name=jeyojeyojeyo+and+fast+are+one+and+the+same",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "no X link ",
      "xUrl": "no X link ",
      "tgHandle": "351175795",
      "rank": 36,
      "flexCards": []
    },
    {
      "name": "BigHammer ",
      "handle": "@joebangsjr",
      "avatar": "https://unavatar.io/twitter/joebangsjr",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/joebangsjr",
      "xUrl": "https://x.com/joebangsjr",
      "tgHandle": "@BigHammer",
      "rank": 37,
      "flexCards": []
    },
    {
      "name": "AltcoinMatcha",
      "handle": "@AltcoinMatcha",
      "avatar": "https://unavatar.io/twitter/AltcoinMatcha",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/AltcoinMatcha",
      "xUrl": "https://x.com/AltcoinMatcha",
      "tgHandle": "@AltcoinMatcha",
      "rank": 38,
      "flexCards": []
    },
    {
      "name": "Lyvo",
      "handle": "@LyvoCrypto",
      "avatar": "https://unavatar.io/twitter/LyvoCrypto",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/lyvocrypto",
      "xUrl": "https://x.com/lyvocrypto",
      "tgHandle": "@LyvoCrypto",
      "rank": 39,
      "flexCards": []
    },
    {
      "name": "Techy0x",
      "handle": "@techy0x",
      "avatar": "https://unavatar.io/twitter/techy0x",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/techy0x",
      "xUrl": "https://x.com/techy0x",
      "tgHandle": "@techy0x",
      "rank": 40,
      "flexCards": []
    },
    {
      "name": "Don_Sama_1",
      "handle": "@Don_Sama_1",
      "avatar": "https://unavatar.io/twitter/Don_Sama_1",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/Don_Sama_1",
      "xUrl": "https://x.com/Don_Sama_1",
      "tgHandle": "1156835258",
      "rank": 41,
      "flexCards": []
    },
    {
      "name": "jyprop",
      "handle": "@prolabch",
      "avatar": "https://unavatar.io/twitter/prolabch",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/prolabch",
      "xUrl": "https://x.com/prolabch",
      "tgHandle": "@jyprop",
      "rank": 42,
      "flexCards": []
    },
    {
      "name": "Devdosomething ",
      "handle": "@devdosomething",
      "avatar": "https://unavatar.io/twitter/devdosomething",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/devdosomething",
      "xUrl": "https://x.com/devdosomething",
      "tgHandle": "@Devdosomething",
      "rank": 43,
      "flexCards": []
    }
  ],
  "monthly": [
    {
      "name": "Rb3k ",
      "handle": "@rbthreek",
      "avatar": "https://unavatar.io/twitter/rbthreek",
      "tweetScore": 0.0,
      "botActivityScore": 121.07,
      "total": 121.07,
      "profileUrl": "https://x.com/rbthreek",
      "xUrl": "https://x.com/rbthreek",
      "tgHandle": "@rbthreek",
      "rank": 1,
      "flexCards": []
    },
    {
      "name": "Chiron \n",
      "handle": "@chironchain",
      "avatar": "https://unavatar.io/twitter/chironchain",
      "tweetScore": 0.0,
      "botActivityScore": 40.13,
      "total": 40.13,
      "profileUrl": "https://x.com/chironchain",
      "xUrl": "https://x.com/chironchain",
      "tgHandle": "@chironthetrader",
      "rank": 2,
      "flexCards": []
    },
    {
      "name": "@KAPOTHEGOAT01\n",
      "handle": "@KAPOTHEGOAT01",
      "avatar": "https://unavatar.io/twitter/KAPOTHEGOAT01",
      "tweetScore": 20.81,
      "botActivityScore": 0.0,
      "total": 20.81,
      "profileUrl": "https://x.com/KAPOTHEGOAT01",
      "xUrl": "https://x.com/KAPOTHEGOAT01",
      "tgHandle": "@LUCKYL1MG",
      "rank": 3,
      "flexCards": []
    },
    {
      "name": "Chainriffs",
      "handle": "@Chainriffs",
      "avatar": "https://unavatar.io/twitter/Chainriffs",
      "tweetScore": 14.43,
      "botActivityScore": 0.0,
      "total": 14.43,
      "profileUrl": "https://x.com/Chainriffs",
      "xUrl": "https://x.com/Chainriffs",
      "tgHandle": "@Chainriffss",
      "rank": 4,
      "flexCards": []
    },
    {
      "name": "cryptocchio0",
      "handle": "@mrLCguy",
      "avatar": "https://unavatar.io/twitter/mrLCguy",
      "tweetScore": 6.7,
      "botActivityScore": 0.0,
      "total": 6.7,
      "profileUrl": "https://x.com/mrlcguy",
      "xUrl": "https://x.com/mrlcguy",
      "tgHandle": "@cryptocchio0",
      "rank": 5,
      "flexCards": []
    },
    {
      "name": "Premium Mind  ( @deepseektetra on X )",
      "handle": "@deepseektetra",
      "avatar": "https://unavatar.io/twitter/deepseektetra",
      "tweetScore": 4.67,
      "botActivityScore": 0.0,
      "total": 4.67,
      "profileUrl": "https://x.com/deepseektetra",
      "xUrl": "https://x.com/deepseektetra",
      "tgHandle": "@tetra528",
      "rank": 6,
      "flexCards": []
    },
    {
      "name": "N30 ",
      "handle": "@N30_cryptoo",
      "avatar": "https://unavatar.io/twitter/N30_cryptoo",
      "tweetScore": 3.39,
      "botActivityScore": 0.0,
      "total": 3.39,
      "profileUrl": "https://x.com/N30_cryptoo",
      "xUrl": "https://x.com/N30_cryptoo",
      "tgHandle": "@N30_CRYPTO",
      "rank": 7,
      "flexCards": []
    },
    {
      "name": "Tyler Kenny ",
      "handle": "@thebasedfrogx",
      "avatar": "https://unavatar.io/twitter/thebasedfrogx",
      "tweetScore": 0.0,
      "botActivityScore": 3.32,
      "total": 3.32,
      "profileUrl": "https://x.com/thebasedfrogx",
      "xUrl": "https://x.com/thebasedfrogx",
      "tgHandle": "@thebasedfrog",
      "rank": 8,
      "flexCards": []
    },
    {
      "name": "cryptic_t",
      "handle": "@cryptic_tits",
      "avatar": "https://unavatar.io/twitter/cryptic_tits",
      "tweetScore": 0.69,
      "botActivityScore": 0.0,
      "total": 0.69,
      "profileUrl": "https://x.com/cryptic_tits",
      "xUrl": "https://x.com/cryptic_tits",
      "tgHandle": "@cryptic_t",
      "rank": 9,
      "flexCards": []
    },
    {
      "name": "neo lawyer ",
      "handle": "@Neolawyer1",
      "avatar": "https://unavatar.io/twitter/Neolawyer1",
      "tweetScore": 0.0,
      "botActivityScore": 0.02,
      "total": 0.02,
      "profileUrl": "https://x.com/Neolawyer1",
      "xUrl": "https://x.com/Neolawyer1",
      "tgHandle": "@Neolawyer",
      "rank": 10,
      "flexCards": []
    },
    {
      "name": "Base Pop",
      "handle": "@KD11201",
      "avatar": "https://unavatar.io/twitter/KD11201",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/KD11201",
      "xUrl": "https://x.com/KD11201",
      "tgHandle": "@Kd11201",
      "rank": 11,
      "flexCards": []
    },
    {
      "name": "Anderson",
      "handle": "@0x7_anderson",
      "avatar": "https://unavatar.io/twitter/0x7_anderson",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/0x7_anderson",
      "xUrl": "https://x.com/0x7_anderson",
      "tgHandle": "@tarcioanderson",
      "rank": 12,
      "flexCards": []
    },
    {
      "name": "Thegardner",
      "handle": "@thegardener777",
      "avatar": "https://unavatar.io/twitter/thegardener777",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/thegardener777",
      "xUrl": "https://x.com/thegardener777",
      "tgHandle": "@thegardener777",
      "rank": 13,
      "flexCards": []
    },
    {
      "name": "Karaiso",
      "handle": "@karaiso4",
      "avatar": "https://unavatar.io/twitter/karaiso4",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/karaiso4",
      "xUrl": "https://x.com/karaiso4",
      "tgHandle": "@karaiso",
      "rank": 14,
      "flexCards": []
    },
    {
      "name": "Math",
      "handle": "@mathburn666",
      "avatar": "https://unavatar.io/twitter/mathburn666",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/mathburn666",
      "xUrl": "https://x.com/mathburn666",
      "tgHandle": "@mathburn666",
      "rank": 15,
      "flexCards": []
    },
    {
      "name": "SexCaliber ",
      "handle": "@Sexcalibur31",
      "avatar": "https://unavatar.io/twitter/Sexcalibur31",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/Sexcalibur31",
      "xUrl": "https://x.com/Sexcalibur31",
      "tgHandle": "@sexcalibur31",
      "rank": 16,
      "flexCards": []
    },
    {
      "name": "RN03xx",
      "handle": "@_RN03xx_",
      "avatar": "https://unavatar.io/twitter/_RN03xx_",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/_RN03xx_",
      "xUrl": "https://x.com/_RN03xx_",
      "tgHandle": "@RN03xx",
      "rank": 17,
      "flexCards": []
    },
    {
      "name": "Borny ",
      "handle": "@unborninfinite",
      "avatar": "https://unavatar.io/twitter/unborninfinite",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/unborninfinite",
      "xUrl": "https://x.com/unborninfinite",
      "tgHandle": "@veryborny",
      "rank": 18,
      "flexCards": []
    },
    {
      "name": "poorad",
      "handle": "@Pooorad",
      "avatar": "https://unavatar.io/twitter/Pooorad",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/Pooorad",
      "xUrl": "https://x.com/Pooorad",
      "tgHandle": "@I_Love_Dogs21",
      "rank": 19,
      "flexCards": []
    },
    {
      "name": "AltcoinMiyagi",
      "handle": "@AltcoinMiyagi",
      "avatar": "https://unavatar.io/twitter/AltcoinMiyagi",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/AltcoinMiyagi",
      "xUrl": "https://x.com/AltcoinMiyagi",
      "tgHandle": "@altcoinmiyagi",
      "rank": 20,
      "flexCards": []
    },
    {
      "name": "acespades34",
      "handle": "@acespades34",
      "avatar": "https://ui-avatars.com/api/?name=acespades34",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "no x link ",
      "xUrl": "no x link ",
      "tgHandle": "5200281793",
      "rank": 21,
      "flexCards": []
    },
    {
      "name": "Alf ",
      "handle": "@alfy11116",
      "avatar": "https://unavatar.io/twitter/alfy11116",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/alfy11116",
      "xUrl": "https://x.com/alfy11116",
      "tgHandle": "@aLfy116",
      "rank": 22,
      "flexCards": []
    },
    {
      "name": "Flynn ",
      "handle": "@Flynn_howitt",
      "avatar": "https://unavatar.io/twitter/Flynn_howitt",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/Flynn_howitt",
      "xUrl": "https://x.com/Flynn_howitt",
      "tgHandle": "@Flynn180",
      "rank": 23,
      "flexCards": []
    },
    {
      "name": "Mj (@vanxryus on X) ",
      "handle": "@Vanxyrus",
      "avatar": "https://unavatar.io/twitter/Vanxyrus",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/Vanxyrus",
      "xUrl": "https://x.com/Vanxyrus",
      "tgHandle": "@Vanxyrus",
      "rank": 24,
      "flexCards": []
    },
    {
      "name": "Medbdy",
      "handle": "@medbdy",
      "avatar": "https://unavatar.io/twitter/medbdy",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/medbdy",
      "xUrl": "https://x.com/medbdy",
      "tgHandle": "@Medbdy7",
      "rank": 25,
      "flexCards": []
    },
    {
      "name": "Zeus ",
      "handle": "@vlagudfsfjr",
      "avatar": "https://unavatar.io/twitter/vlagudfsfjr",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/vlagudfsfjr",
      "xUrl": "https://x.com/vlagudfsfjr",
      "tgHandle": "@zeus4r",
      "rank": 26,
      "flexCards": []
    },
    {
      "name": "Shake ",
      "handle": "@Shake51_",
      "avatar": "https://unavatar.io/twitter/Shake51_",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/Shake51_",
      "xUrl": "https://x.com/Shake51_",
      "tgHandle": "@Shake51",
      "rank": 27,
      "flexCards": []
    },
    {
      "name": "Social Block ",
      "handle": "@socialblock",
      "avatar": "https://ui-avatars.com/api/?name=Social+Block+",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "no X link",
      "xUrl": "no X link",
      "tgHandle": "8349346803",
      "rank": 28,
      "flexCards": []
    },
    {
      "name": "DJ (@NLinker777 on X )",
      "handle": "@NLinker777",
      "avatar": "https://unavatar.io/twitter/NLinker777",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/NLinker777",
      "xUrl": "https://x.com/NLinker777",
      "tgHandle": "@JIHANWOOOO",
      "rank": 29,
      "flexCards": []
    },
    {
      "name": "Spenny",
      "handle": "@SpennyCrypto",
      "avatar": "https://unavatar.io/twitter/SpennyCrypto",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/SpennyCrypto",
      "xUrl": "https://x.com/SpennyCrypto",
      "tgHandle": "@spennypretzel",
      "rank": 30,
      "flexCards": []
    },
    {
      "name": "Nouyarao",
      "handle": "@sentientom",
      "avatar": "https://unavatar.io/twitter/sentientom",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/sentientom",
      "xUrl": "https://x.com/sentientom",
      "tgHandle": "@Nouyarao",
      "rank": 31,
      "flexCards": []
    },
    {
      "name": "mDiBe89",
      "handle": "@tibbiracer",
      "avatar": "https://unavatar.io/twitter/tibbiracer",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/tibbiracer",
      "xUrl": "https://x.com/tibbiracer",
      "tgHandle": "@mDiBe89",
      "rank": 32,
      "flexCards": []
    },
    {
      "name": "Debankind ",
      "handle": "@DebankinDad",
      "avatar": "https://unavatar.io/twitter/DebankinDad",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/DebankinDad",
      "xUrl": "https://x.com/DebankinDad",
      "tgHandle": "DebankinDad",
      "rank": 33,
      "flexCards": []
    },
    {
      "name": "3Dmax",
      "handle": "@3DMax_Virtuals",
      "avatar": "https://unavatar.io/twitter/3DMax_Virtuals",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/3DMax_Virtuals",
      "xUrl": "https://x.com/3DMax_Virtuals",
      "tgHandle": "@oO_3Dmax",
      "rank": 34,
      "flexCards": []
    },
    {
      "name": "arindewar",
      "handle": "@arindewar",
      "avatar": "https://unavatar.io/twitter/arindewar",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/arindewar",
      "xUrl": "https://x.com/arindewar",
      "tgHandle": "@arrieindewarrie",
      "rank": 35,
      "flexCards": []
    },
    {
      "name": "jeyojeyojeyo and fast are one and the same",
      "handle": "@jeyojeyojeyoandfastareoneandthesame",
      "avatar": "https://ui-avatars.com/api/?name=jeyojeyojeyo+and+fast+are+one+and+the+same",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "no X link ",
      "xUrl": "no X link ",
      "tgHandle": "351175795",
      "rank": 36,
      "flexCards": []
    },
    {
      "name": "BigHammer ",
      "handle": "@joebangsjr",
      "avatar": "https://unavatar.io/twitter/joebangsjr",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/joebangsjr",
      "xUrl": "https://x.com/joebangsjr",
      "tgHandle": "@BigHammer",
      "rank": 37,
      "flexCards": []
    },
    {
      "name": "AltcoinMatcha",
      "handle": "@AltcoinMatcha",
      "avatar": "https://unavatar.io/twitter/AltcoinMatcha",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/AltcoinMatcha",
      "xUrl": "https://x.com/AltcoinMatcha",
      "tgHandle": "@AltcoinMatcha",
      "rank": 38,
      "flexCards": []
    },
    {
      "name": "Lyvo",
      "handle": "@LyvoCrypto",
      "avatar": "https://unavatar.io/twitter/LyvoCrypto",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/lyvocrypto",
      "xUrl": "https://x.com/lyvocrypto",
      "tgHandle": "@LyvoCrypto",
      "rank": 39,
      "flexCards": []
    },
    {
      "name": "Techy0x",
      "handle": "@techy0x",
      "avatar": "https://unavatar.io/twitter/techy0x",
      "tweetScore": 0.0,
      "botActivityScore": 0.0,
      "total": 0.0,
      "profileUrl": "https://x.com/techy0x",
      "xUrl": "https://x.com/techy0x",
      "tgHandle": "@techy0x",
      "rank": 40,
      "flexCards": []
    },
    {
      "name": "Don_Sama_1",
      "handle": "@Don_Sama_1",
      "avatar": "https://unavatar.io/twitter/Don_Sama_1",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/Don_Sama_1",
      "xUrl": "https://x.com/Don_Sama_1",
      "tgHandle": "1156835258",
      "rank": 41,
      "flexCards": []
    },
    {
      "name": "jyprop",
      "handle": "@prolabch",
      "avatar": "https://unavatar.io/twitter/prolabch",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/prolabch",
      "xUrl": "https://x.com/prolabch",
      "tgHandle": "@jyprop",
      "rank": 42,
      "flexCards": []
    },
    {
      "name": "Devdosomething ",
      "handle": "@devdosomething",
      "avatar": "https://unavatar.io/twitter/devdosomething",
      "tweetScore": 0,
      "botActivityScore": 0,
      "total": 0,
      "profileUrl": "https://x.com/devdosomething",
      "xUrl": "https://x.com/devdosomething",
      "tgHandle": "@Devdosomething",
      "rank": 43,
      "flexCards": []
    }
  ]
};
